[workspace]
[package]
version = "0.1.0"
name = "uint256-arith-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-derive = { git = "https://github.com/succinctlabs/sp1.git" }
crypto-bigint = "0.6.0-pre.12"