[workspace]
[package]
version = "0.1.0"
name = "io-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
serde = { version = "1.0.136", features = ["derive"] }