[workspace]
[package]
version = "0.1.0"
name = "io-script"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
serde = { version = "1.0.196", features = ["derive"] }

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }